POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "test1",
    "email": "user1@email.com",
    "password": "#Password123"
}

###

POST http://localhost:8080/api/auth/session/login
Content-Type: application/json

{
    "username": "test1",
    "password": "#Password123"
}

###

POST http://localhost:8080/api/auth/token/login
Content-Type: application/json

{
    "username": "test",
    "password": "#Password123"
}

###
GET http://localhost:8080/api/auth/session/user
Content-Type: application/json

{
    "username": "test",
    "password": "#Password123"
}

###

POST http://localhost:8080/api/auth/logout

###

POST http://localhost:8080/api/auth/update/password
Content-Type: application/json

{
    "credentials": {
        "username": "test",
        "password": "#Password123"
    },
    "update": {
        "username": "user",
        "email": "user2@email.com",
        "password": "#Password123",
    }
}