POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "username": "test",
    "email": "user@email.com",
    "password": "#Password123"
}

###

POST http://localhost:8080/api/auth/session/login
Content-Type: application/json

{
    "username": "test",
    "password": "#Password123"
}

###

POST http://localhost:8080/api/auth/session/login/token
Content-Type: application/json

{
    "username": "test",
    "password": "#Password123"
}

###
GET http://localhost:8080/api/auth/session/user
Content-Type: application/json

{
    "username": "test",
    "password": "#Password123"
}

###

POST http://localhost:8080/api/auth/logout