// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gsk "github.com/adharshmk96/stk/gsk"
	mock "github.com/stretchr/testify/mock"
)

// AccountHandler is an autogenerated mock type for the AccountHandler type
type AccountHandler struct {
	mock.Mock
}

// GetSessionTokenUser provides a mock function with given fields: ctx
func (_m *AccountHandler) GetSessionTokenUser(ctx gsk.Context) {
	_m.Called(ctx)
}

// GetSessionUser provides a mock function with given fields: ctx
func (_m *AccountHandler) GetSessionUser(ctx gsk.Context) {
	_m.Called(ctx)
}

// LoginUserSession provides a mock function with given fields: ctx
func (_m *AccountHandler) LoginUserSession(ctx gsk.Context) {
	_m.Called(ctx)
}

// LoginUserToken provides a mock function with given fields: ctx
func (_m *AccountHandler) LoginUserToken(ctx gsk.Context) {
	_m.Called(ctx)
}

// LogoutUser provides a mock function with given fields: ctx
func (_m *AccountHandler) LogoutUser(ctx gsk.Context) {
	_m.Called(ctx)
}

// RegisterUser provides a mock function with given fields: ctx
func (_m *AccountHandler) RegisterUser(ctx gsk.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewAccountHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewAccountHandler creates a new instance of AccountHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAccountHandler(t mockConstructorTestingTNewAccountHandler) *AccountHandler {
	mock := &AccountHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
