// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	gsk "github.com/adharshmk96/stk/gsk"
	mock "github.com/stretchr/testify/mock"
)

// AccountHandlers is an autogenerated mock type for the AccountHandlers type
type AccountHandlers struct {
	mock.Mock
}

// AccountDetails provides a mock function with given fields: gc
func (_m *AccountHandlers) AccountDetails(gc *gsk.Context) {
	_m.Called(gc)
}

// LoginWithGoogle provides a mock function with given fields: gc
func (_m *AccountHandlers) LoginWithGoogle(gc *gsk.Context) {
	_m.Called(gc)
}

// LoginWithGoogleCallback provides a mock function with given fields: gc
func (_m *AccountHandlers) LoginWithGoogleCallback(gc *gsk.Context) {
	_m.Called(gc)
}

// Logout provides a mock function with given fields: gc
func (_m *AccountHandlers) Logout(gc *gsk.Context) {
	_m.Called(gc)
}

// NewAccountHandlers creates a new instance of AccountHandlers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountHandlers(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountHandlers {
	mock := &AccountHandlers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
