// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gsk "github.com/adharshmk96/stk/gsk"
	mock "github.com/stretchr/testify/mock"
)

// AccountHandler is an autogenerated mock type for the AccountHandler type
type AccountHandler struct {
	mock.Mock
}

// ChangeCredentials provides a mock function with given fields: gc
func (_m *AccountHandler) ChangeCredentials(gc *gsk.Context) {
	_m.Called(gc)
}

// GetUserList provides a mock function with given fields: gc
func (_m *AccountHandler) GetUserList(gc *gsk.Context) {
	_m.Called(gc)
}

// RegisterUser provides a mock function with given fields: gc
func (_m *AccountHandler) RegisterUser(gc *gsk.Context) {
	_m.Called(gc)
}

type mockConstructorTestingTNewAccountHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewAccountHandler creates a new instance of AccountHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAccountHandler(t mockConstructorTestingTNewAccountHandler) *AccountHandler {
	mock := &AccountHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
