// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AdministrationHandler is an autogenerated mock type for the AdministrationHandler type
type AdministrationHandler struct {
	mock.Mock
}

type mockConstructorTestingTNewAdministrationHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewAdministrationHandler creates a new instance of AdministrationHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAdministrationHandler(t mockConstructorTestingTNewAdministrationHandler) *AdministrationHandler {
	mock := &AdministrationHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
