// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gsk "github.com/adharshmk96/stk/gsk"
	mock "github.com/stretchr/testify/mock"
)

// AdminHandler is an autogenerated mock type for the AdminHandler type
type AdminHandler struct {
	mock.Mock
}

// CreateGroup provides a mock function with given fields: gc
func (_m *AdminHandler) CreateGroup(gc *gsk.Context) {
	_m.Called(gc)
}

// GetAccountDetails provides a mock function with given fields: gc
func (_m *AdminHandler) GetAccountDetails(gc *gsk.Context) {
	_m.Called(gc)
}

// GetAccountList provides a mock function with given fields: gc
func (_m *AdminHandler) GetAccountList(gc *gsk.Context) {
	_m.Called(gc)
}

type mockConstructorTestingTNewAdminHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewAdminHandler creates a new instance of AdminHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAdminHandler(t mockConstructorTestingTNewAdminHandler) *AdminHandler {
	mock := &AdminHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
