// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gsk "github.com/adharshmk96/stk/gsk"
	mock "github.com/stretchr/testify/mock"
)

// AuthenticationHandler is an autogenerated mock type for the AuthenticationHandler type
type AuthenticationHandler struct {
	mock.Mock
}

// ChangeCredentials provides a mock function with given fields: gc
func (_m *AuthenticationHandler) ChangeCredentials(gc *gsk.Context) {
	_m.Called(gc)
}

// GetSessionAccount provides a mock function with given fields: gc
func (_m *AuthenticationHandler) GetSessionAccount(gc *gsk.Context) {
	_m.Called(gc)
}

// GetTokenAccount provides a mock function with given fields: gc
func (_m *AuthenticationHandler) GetTokenAccount(gc *gsk.Context) {
	_m.Called(gc)
}

// LoginAccountSession provides a mock function with given fields: gc
func (_m *AuthenticationHandler) LoginAccountSession(gc *gsk.Context) {
	_m.Called(gc)
}

// LoginAccountToken provides a mock function with given fields: gc
func (_m *AuthenticationHandler) LoginAccountToken(gc *gsk.Context) {
	_m.Called(gc)
}

// LogoutAccount provides a mock function with given fields: gc
func (_m *AuthenticationHandler) LogoutAccount(gc *gsk.Context) {
	_m.Called(gc)
}

// RegisterAccount provides a mock function with given fields: gc
func (_m *AuthenticationHandler) RegisterAccount(gc *gsk.Context) {
	_m.Called(gc)
}

// ResetPassword provides a mock function with given fields: gc
func (_m *AuthenticationHandler) ResetPassword(gc *gsk.Context) {
	_m.Called(gc)
}

type mockConstructorTestingTNewAuthenticationHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthenticationHandler creates a new instance of AuthenticationHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthenticationHandler(t mockConstructorTestingTNewAuthenticationHandler) *AuthenticationHandler {
	mock := &AuthenticationHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
