// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	entities "github.com/adharshmk96/stk-auth/pkg/entities"
	ds "github.com/adharshmk96/stk-auth/pkg/entities/ds"

	mock "github.com/stretchr/testify/mock"
)

// AuthenticationService is an autogenerated mock type for the AuthenticationService type
type AuthenticationService struct {
	mock.Mock
}

// AddAccountToGroup provides a mock function with given fields: accountId, groupId
func (_m *AuthenticationService) AddAccountToGroup(accountId ds.AccountID, groupId string) error {
	ret := _m.Called(accountId, groupId)

	var r0 error
	if rf, ok := ret.Get(0).(func(ds.AccountID, string) error); ok {
		r0 = rf(accountId, groupId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Authenticate provides a mock function with given fields: login
func (_m *AuthenticationService) Authenticate(login *ds.Account) error {
	ret := _m.Called(login)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ds.Account) error); ok {
		r0 = rf(login)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangePassword provides a mock function with given fields: account
func (_m *AuthenticationService) ChangePassword(account *ds.Account) error {
	ret := _m.Called(account)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ds.Account) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckAccountInGroup provides a mock function with given fields: accountId, groupId
func (_m *AuthenticationService) CheckAccountInGroup(accountId ds.AccountID, groupId string) (bool, error) {
	ret := _m.Called(accountId, groupId)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(ds.AccountID, string) (bool, error)); ok {
		return rf(accountId, groupId)
	}
	if rf, ok := ret.Get(0).(func(ds.AccountID, string) bool); ok {
		r0 = rf(accountId, groupId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(ds.AccountID, string) error); ok {
		r1 = rf(accountId, groupId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateAccount provides a mock function with given fields: account
func (_m *AuthenticationService) CreateAccount(account *ds.Account) (*ds.Account, error) {
	ret := _m.Called(account)

	var r0 *ds.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(*ds.Account) (*ds.Account, error)); ok {
		return rf(account)
	}
	if rf, ok := ret.Get(0).(func(*ds.Account) *ds.Account); ok {
		r0 = rf(account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ds.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(*ds.Account) error); ok {
		r1 = rf(account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateGroup provides a mock function with given fields: group
func (_m *AuthenticationService) CreateGroup(group *ds.Group) (*ds.Group, error) {
	ret := _m.Called(group)

	var r0 *ds.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(*ds.Group) (*ds.Group, error)); ok {
		return rf(group)
	}
	if rf, ok := ret.Get(0).(func(*ds.Group) *ds.Group); ok {
		r0 = rf(group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ds.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(*ds.Group) error); ok {
		r1 = rf(group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateSession provides a mock function with given fields: account
func (_m *AuthenticationService) CreateSession(account *ds.Account) (*ds.Session, error) {
	ret := _m.Called(account)

	var r0 *ds.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(*ds.Account) (*ds.Session, error)); ok {
		return rf(account)
	}
	if rf, ok := ret.Get(0).(func(*ds.Account) *ds.Session); ok {
		r0 = rf(account)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ds.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(*ds.Account) error); ok {
		r1 = rf(account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteGroupByID provides a mock function with given fields: groupId
func (_m *AuthenticationService) DeleteGroupByID(groupId string) error {
	ret := _m.Called(groupId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(groupId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateJWT provides a mock function with given fields: claims
func (_m *AuthenticationService) GenerateJWT(claims *entities.CustomClaims) (string, error) {
	ret := _m.Called(claims)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.CustomClaims) (string, error)); ok {
		return rf(claims)
	}
	if rf, ok := ret.Get(0).(func(*entities.CustomClaims) string); ok {
		r0 = rf(claims)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*entities.CustomClaims) error); ok {
		r1 = rf(claims)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountByID provides a mock function with given fields: accountId
func (_m *AuthenticationService) GetAccountByID(accountId string) (*ds.Account, error) {
	ret := _m.Called(accountId)

	var r0 *ds.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*ds.Account, error)); ok {
		return rf(accountId)
	}
	if rf, ok := ret.Get(0).(func(string) *ds.Account); ok {
		r0 = rf(accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ds.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(accountId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountBySessionId provides a mock function with given fields: sessionId
func (_m *AuthenticationService) GetAccountBySessionId(sessionId string) (*ds.Account, error) {
	ret := _m.Called(sessionId)

	var r0 *ds.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*ds.Account, error)); ok {
		return rf(sessionId)
	}
	if rf, ok := ret.Get(0).(func(string) *ds.Account); ok {
		r0 = rf(sessionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ds.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sessionId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountDetails provides a mock function with given fields: accountId
func (_m *AuthenticationService) GetAccountDetails(accountId ds.AccountID) (*ds.Account, error) {
	ret := _m.Called(accountId)

	var r0 *ds.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(ds.AccountID) (*ds.Account, error)); ok {
		return rf(accountId)
	}
	if rf, ok := ret.Get(0).(func(ds.AccountID) *ds.Account); ok {
		r0 = rf(accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ds.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(ds.AccountID) error); ok {
		r1 = rf(accountId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccountList provides a mock function with given fields: limit, offset
func (_m *AuthenticationService) GetAccountList(limit int, offset int) ([]*ds.Account, error) {
	ret := _m.Called(limit, offset)

	var r0 []*ds.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) ([]*ds.Account, error)); ok {
		return rf(limit, offset)
	}
	if rf, ok := ret.Get(0).(func(int, int) []*ds.Account); ok {
		r0 = rf(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ds.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGroupsByAccountID provides a mock function with given fields: accountId
func (_m *AuthenticationService) GetGroupsByAccountID(accountId ds.AccountID) ([]*ds.Group, error) {
	ret := _m.Called(accountId)

	var r0 []*ds.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(ds.AccountID) ([]*ds.Group, error)); ok {
		return rf(accountId)
	}
	if rf, ok := ret.Get(0).(func(ds.AccountID) []*ds.Group); ok {
		r0 = rf(accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ds.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(ds.AccountID) error); ok {
		r1 = rf(accountId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalAccountsCount provides a mock function with given fields:
func (_m *AuthenticationService) GetTotalAccountsCount() (int64, error) {
	ret := _m.Called()

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func() (int64, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogoutAccountBySessionId provides a mock function with given fields: sessionId
func (_m *AuthenticationService) LogoutAccountBySessionId(sessionId string) error {
	ret := _m.Called(sessionId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(sessionId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveAccountFromGroup provides a mock function with given fields: accountId, groupId
func (_m *AuthenticationService) RemoveAccountFromGroup(accountId ds.AccountID, groupId string) error {
	ret := _m.Called(accountId, groupId)

	var r0 error
	if rf, ok := ret.Get(0).(func(ds.AccountID, string) error); ok {
		r0 = rf(accountId, groupId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResetPassword provides a mock function with given fields: account, password
func (_m *AuthenticationService) ResetPassword(account string, password string) error {
	ret := _m.Called(account, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(account, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendPasswordResetEmail provides a mock function with given fields: email, sender
func (_m *AuthenticationService) SendPasswordResetEmail(email string, sender func(string, string) error) error {
	ret := _m.Called(email, sender)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func(string, string) error) error); ok {
		r0 = rf(email, sender)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateGroupByID provides a mock function with given fields: group
func (_m *AuthenticationService) UpdateGroupByID(group *ds.Group) error {
	ret := _m.Called(group)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ds.Group) error); ok {
		r0 = rf(group)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateJWT provides a mock function with given fields: token
func (_m *AuthenticationService) ValidateJWT(token string) (*entities.CustomClaims, error) {
	ret := _m.Called(token)

	var r0 *entities.CustomClaims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*entities.CustomClaims, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *entities.CustomClaims); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.CustomClaims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAuthenticationService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthenticationService creates a new instance of AuthenticationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthenticationService(t mockConstructorTestingTNewAuthenticationService) *AuthenticationService {
	mock := &AuthenticationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
