// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gsk "github.com/adharshmk96/stk/gsk"
	mock "github.com/stretchr/testify/mock"
)

// GroupHandler is an autogenerated mock type for the GroupHandler type
type GroupHandler struct {
	mock.Mock
}

// CreateGroup provides a mock function with given fields: gc
func (_m *GroupHandler) CreateGroup(gc gsk.Context) {
	_m.Called(gc)
}

type mockConstructorTestingTNewGroupHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewGroupHandler creates a new instance of GroupHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGroupHandler(t mockConstructorTestingTNewGroupHandler) *GroupHandler {
	mock := &GroupHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
