// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	ds "github.com/adharshmk96/stk-auth/pkg/entities/ds"

	mock "github.com/stretchr/testify/mock"
)

// groupService is an autogenerated mock type for the groupService type
type groupService struct {
	mock.Mock
}

// AddAccountToGroup provides a mock function with given fields: accountId, groupId
func (_m *groupService) AddAccountToGroup(accountId ds.AccountID, groupId string) error {
	ret := _m.Called(accountId, groupId)

	var r0 error
	if rf, ok := ret.Get(0).(func(ds.AccountID, string) error); ok {
		r0 = rf(accountId, groupId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckAccountInGroup provides a mock function with given fields: accountId, groupId
func (_m *groupService) CheckAccountInGroup(accountId ds.AccountID, groupId string) (bool, error) {
	ret := _m.Called(accountId, groupId)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(ds.AccountID, string) (bool, error)); ok {
		return rf(accountId, groupId)
	}
	if rf, ok := ret.Get(0).(func(ds.AccountID, string) bool); ok {
		r0 = rf(accountId, groupId)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(ds.AccountID, string) error); ok {
		r1 = rf(accountId, groupId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateGroup provides a mock function with given fields: group
func (_m *groupService) CreateGroup(group *ds.Group) (*ds.Group, error) {
	ret := _m.Called(group)

	var r0 *ds.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(*ds.Group) (*ds.Group, error)); ok {
		return rf(group)
	}
	if rf, ok := ret.Get(0).(func(*ds.Group) *ds.Group); ok {
		r0 = rf(group)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ds.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(*ds.Group) error); ok {
		r1 = rf(group)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteGroupByID provides a mock function with given fields: groupId
func (_m *groupService) DeleteGroupByID(groupId string) error {
	ret := _m.Called(groupId)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(groupId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetGroupsByAccountID provides a mock function with given fields: accountId
func (_m *groupService) GetGroupsByAccountID(accountId ds.AccountID) ([]*ds.Group, error) {
	ret := _m.Called(accountId)

	var r0 []*ds.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(ds.AccountID) ([]*ds.Group, error)); ok {
		return rf(accountId)
	}
	if rf, ok := ret.Get(0).(func(ds.AccountID) []*ds.Group); ok {
		r0 = rf(accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ds.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(ds.AccountID) error); ok {
		r1 = rf(accountId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveAccountFromGroup provides a mock function with given fields: accountId, groupId
func (_m *groupService) RemoveAccountFromGroup(accountId ds.AccountID, groupId string) error {
	ret := _m.Called(accountId, groupId)

	var r0 error
	if rf, ok := ret.Get(0).(func(ds.AccountID, string) error); ok {
		r0 = rf(accountId, groupId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateGroupByID provides a mock function with given fields: group
func (_m *groupService) UpdateGroupByID(group *ds.Group) error {
	ret := _m.Called(group)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ds.Group) error); ok {
		r0 = rf(group)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewGroupService interface {
	mock.TestingT
	Cleanup(func())
}

// newGroupService creates a new instance of groupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newGroupService(t mockConstructorTestingTnewGroupService) *groupService {
	mock := &groupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
