// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gsk "github.com/adharshmk96/stk/gsk"
	mock "github.com/stretchr/testify/mock"
)

// OauthHandler is an autogenerated mock type for the OauthHandler type
type OauthHandler struct {
	mock.Mock
}

// GoogleOauthCallback provides a mock function with given fields: gc
func (_m *OauthHandler) GoogleOauthCallback(gc *gsk.Context) {
	_m.Called(gc)
}

// GoogleOauthLogin provides a mock function with given fields: gc
func (_m *OauthHandler) GoogleOauthLogin(gc *gsk.Context) {
	_m.Called(gc)
}

type mockConstructorTestingTNewOauthHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewOauthHandler creates a new instance of OauthHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOauthHandler(t mockConstructorTestingTNewOauthHandler) *OauthHandler {
	mock := &OauthHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
