// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gsk "github.com/adharshmk96/stk/gsk"
	mock "github.com/stretchr/testify/mock"
)

// userHandler is an autogenerated mock type for the userHandler type
type userHandler struct {
	mock.Mock
}

// ChangeCredentials provides a mock function with given fields: gc
func (_m *userHandler) ChangeCredentials(gc *gsk.Context) {
	_m.Called(gc)
}

// RegisterUser provides a mock function with given fields: gc
func (_m *userHandler) RegisterUser(gc *gsk.Context) {
	_m.Called(gc)
}

type mockConstructorTestingTnewUserHandler interface {
	mock.TestingT
	Cleanup(func())
}

// newUserHandler creates a new instance of userHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newUserHandler(t mockConstructorTestingTnewUserHandler) *userHandler {
	mock := &userHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
